/**
 * Ed25519 public key for tool signature verification (hex-encoded).
 * Generated by: tsx scripts/sign-tools.ts
 * DO NOT edit manually — run the sign-tools script to regenerate.
 */
export const TOOL_SIGNING_PUBLIC_KEY = '68a7e4c616061377a763c3f6bf2b6c9c80223aac82cc37642ee9e2a80e72ccb3'
