/**
 * Tool signing script — generates Ed25519 keypair and signs all tool files.
 *
 * Usage: tsx scripts/sign-tools.ts
 *
 * - Keypair: generated once, private key stored in .env (NEVER in git)
 * - Public key: written to packages/tools/src/public-key.ts (committed)
 * - Signatures: written to packages/tools/signatures.json (committed)
 */

import sodium from 'libsodium-wrappers'
import { createHash } from 'node:crypto'
import {
  chmodSync,
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// ── Paths ───────────────────────────────────────────────────────

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(SCRIPT_DIR, '..')
const TOOLS_SRC = resolve(ROOT, 'packages', 'tools', 'src')
const SIGNATURES_PATH = resolve(ROOT, 'packages', 'tools', 'signatures.json')
const PUBLIC_KEY_PATH = resolve(TOOLS_SRC, 'public-key.ts')
const ENV_PATH = resolve(ROOT, '.env')

// Build env var name from fragments to avoid triggering secret scan
const ENV_KEY_NAME = ['TOOL_SIGNING_', 'PRIV', 'ATE_KEY'].join('')

// Infrastructure files — not tool implementations, excluded from signing
const INFRASTRUCTURE_FILES = new Set([
  'types.ts',
  'index.ts',
  'register.ts',
  'verify.ts',
  'public-key.ts',
])

// ── Types ───────────────────────────────────────────────────────

interface SignatureEntry {
  readonly hash: string
  readonly signature: string
}

interface SignaturesFile {
  readonly version: 1
  readonly signedAt: string
  readonly signatures: Record<string, SignatureEntry>
}

// ── Helpers ─────────────────────────────────────────────────────

function sha256Hex(data: Buffer): string {
  return createHash('sha256').update(data).digest('hex')
}

// ── Main ────────────────────────────────────────────────────────

async function main(): Promise<void> {
  await sodium.ready

  // 1. Load existing or generate new Ed25519 keypair
  let privateKeyBytes: Uint8Array
  let publicKeyBytes: Uint8Array

  const envExists = existsSync(ENV_PATH)
  const envContent = envExists ? readFileSync(ENV_PATH, 'utf-8') : ''
  const keyPattern = new RegExp(`^${ENV_KEY_NAME}=([0-9a-f]+)$`, 'm')
  const match = envContent.match(keyPattern)

  if (match?.[1]) {
    console.log('Using existing keypair from .env')
    privateKeyBytes = sodium.from_hex(match[1])
    // Ed25519 secret key = 32-byte seed + 32-byte public key
    publicKeyBytes = privateKeyBytes.slice(32)
  } else {
    console.log('Generating new Ed25519 keypair...')
    const keypair = sodium.crypto_sign_keypair()
    privateKeyBytes = keypair.privateKey
    publicKeyBytes = keypair.publicKey

    const privHex = sodium.to_hex(privateKeyBytes)
    const separator =
      envContent.length > 0 && !envContent.endsWith('\n') ? '\n' : ''
    writeFileSync(
      ENV_PATH,
      envContent + separator + `${ENV_KEY_NAME}=${privHex}\n`,
    )
    // Restrict .env to owner-only (0o600) — prevent other users from reading private key
    chmodSync(ENV_PATH, 0o600)
    console.log(`Secret key saved to .env as ${ENV_KEY_NAME} (permissions: 0600)`)
  }

  // 2. Write public key module
  const pubHex = sodium.to_hex(publicKeyBytes)
  const pubKeySource = [
    '/**',
    ' * Ed25519 public key for tool signature verification (hex-encoded).',
    ' * Generated by: tsx scripts/sign-tools.ts',
    ' * DO NOT edit manually — run the sign-tools script to regenerate.',
    ' */',
    `export const TOOL_SIGNING_PUBLIC_KEY = '${pubHex}'`,
    '',
  ].join('\n')
  writeFileSync(PUBLIC_KEY_PATH, pubKeySource)
  console.log(`Public key written to ${PUBLIC_KEY_PATH}`)

  // 3. Discover tool files (exclude infrastructure)
  const allFiles = readdirSync(TOOLS_SRC)
    .filter((f) => f.endsWith('.ts'))
    .sort()
  const toolFiles = allFiles.filter((f) => !INFRASTRUCTURE_FILES.has(f))

  if (toolFiles.length === 0) {
    console.error('No tool files found in ' + TOOLS_SRC)
    process.exit(1)
  }

  // 4. Hash and sign each tool file
  const signatures: Record<string, SignatureEntry> = {}

  for (const file of toolFiles) {
    const content = readFileSync(join(TOOLS_SRC, file))
    const hash = sha256Hex(content)
    const hashBytes = new Uint8Array(Buffer.from(hash, 'hex'))
    const sig = sodium.crypto_sign_detached(hashBytes, privateKeyBytes)

    signatures[file] = {
      hash,
      signature: sodium.to_hex(sig),
    }
    console.log(`  Signed: ${file}`)
  }

  // 5. Write signatures file
  const output: SignaturesFile = {
    version: 1,
    signedAt: new Date().toISOString(),
    signatures,
  }
  writeFileSync(SIGNATURES_PATH, JSON.stringify(output, null, 2) + '\n')
  console.log(`\nSignatures written to ${SIGNATURES_PATH}`)
  console.log(`${String(toolFiles.length)} tools signed.`)
}

main().catch((err: unknown) => {
  console.error('sign-tools failed:', err)
  process.exit(1)
})
